### ISSUE TITLE
XML in RS broken

### ISSUE THREAD

**Issue by jadolfbr** [RosettaCommons/PyRosetta.notebooks#54]
The function signature has changed for the parser and this needs to be fixed. Also, debug statements should only not run for long components.  Not sure where that part changed.  I have a branch with this fixed, but for some reason, can't push to the repo.

**Comment by klimaj** [comment]
I may have added debug statements to cells of certain notebooks that produced unit test errors. If you remove dubug statements, please open a PR in `RosettaCommons/main`, pull in Pyrosetta.notebooks submodule updates, and schedule the `03 PyRosetta` tests to queue `PyRosetta4.notebook` unit tests.

**Comment by jadolfbr** [comment]
Those unit test errors were basically saying that this notebook was broken.  Without that - I'm not quite understanding why the testing is happening in first place?

**Comment by klimaj** [comment]
@jadolfbr Much agreed! Ideally those cells were tested before merging, but if I recall correctly those debug statements added in #51 were merely intended as a temporary workaround to permit scheduling `03 PyRosetta` unit tests from PRs in `RosettaCommons/main` (otherwise PyRosetta tests always were failing). Those notebooks cells still need to be addressed.

**Comment by jadolfbr** [comment]
Fixed in most recent version, PR open.
